

2021-07-12_23-22-07
Traceback (most recent call last):
  File "C:\Users\notmu\Documents\Code\Python\magyka\magyka.py", line 1603, in <module>
    screen = Screen()
  File "C:\Users\notmu\Documents\Code\Python\magyka\magyka.py", line 400, in __init__
    next_screen()
  File "C:\Users\notmu\Documents\Code\Python\magyka\magyka.py", line 550, in camp
    Image("background").show_at_origin()
  File "C:\Users\notmu\Documents\Code\Python\magyka\script\Image.py", line 68, in show_at_origin
    self.show(1, 1)
  File "C:\Users\notmu\Documents\Code\Python\magyka\script\Image.py", line 62, in show
    sys.stdout.flush()
NameError: name 'sys' is not defined
 